import os
import requests
import json
import subprocess
import time

OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://localhost:11434")
LLM_TIMEOUT = int(os.environ.get("LLM_TIMEOUT", "120"))

def ensure_ollama_running():
    """
    Check if Ollama server is active on host. If not, attempt to start 'ollama serve' in background.
    """
    try:
        resp = requests.get(f"{OLLAMA_HOST}/api/tags", timeout=2)
        if resp.status_code == 200:
            return True
    except requests.exceptions.RequestException:
        pass

    print("[LLM Warning] Ollama server is not responding. Attempting to start 'ollama serve'...")
    try:
        subprocess.Popen(["ollama", "serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        for _ in range(12):
            time.sleep(0.5)
            try:
                resp = requests.get(f"{OLLAMA_HOST}/api/tags", timeout=2)
                if resp.status_code == 200:
                    print("[LLM Info] Ollama server started successfully.")
                    return True
            except requests.exceptions.RequestException:
                pass
    except Exception as e:
        print(f"[LLM Warning] Failed to start 'ollama serve': {e}")

    return False

def get_available_model(requested_model: str = None) -> str:
    """
    Detect available local Gemma model or select user-requested model.
    """
    if requested_model:
        return requested_model

    env_model = os.environ.get("GEMMA_MODEL")
    if env_model:
        return env_model

    if not ensure_ollama_running():
        raise RuntimeError("Ollama server is not available at http://localhost:11434. Please start Ollama service.")

    try:
        resp = requests.get(f"{OLLAMA_HOST}/api/tags", timeout=3)
        if resp.status_code == 200:
            data = resp.json()
            models = data.get("models", [])
            if not models:
                raise RuntimeError("No local Ollama models found. Please pull a model using 'ollama pull gemma2:2b'.")

            models_sorted = sorted(models, key=lambda x: x.get("size", 0))

            for m in models_sorted:
                name = m.get("name", "")
                if "gemma" in name.lower():
                    return name

            return models_sorted[0].get("name", "")
    except Exception as e:
        raise RuntimeError(f"Error connecting to Ollama: {e}") from e

    return "gemma2:2b"

def query_ollama(prompt: str, model_name: str, system_prompt: str = "") -> str:
    """
    Send generation prompt to Ollama REST API.
    """
    ensure_ollama_running()
    url = f"{OLLAMA_HOST}/api/generate"
    payload = {
        "model": model_name,
        "prompt": prompt,
        "system": system_prompt,
        "stream": False,
        "options": {
            "num_predict": 256,
            "temperature": 0.2
        }
    }

    try:
        response = requests.post(url, json=payload, timeout=LLM_TIMEOUT)
        if response.status_code != 200:
            raise RuntimeError(f"Ollama request failed (HTTP {response.status_code}): {response.text}")
        data = response.json()
        return data.get("response", "").strip()
    except requests.exceptions.Timeout as e:
        raise RuntimeError(
            f"Ollama request timed out after {LLM_TIMEOUT}s. "
            "Try a smaller model or increase LLM_TIMEOUT."
        ) from e
    except requests.exceptions.RequestException as e:
        raise RuntimeError(f"Ollama connection error: {e}") from e

def clean_output_markers(text: str) -> str:
    """
    Strip any stray prompt markers or markdown delimiters if generated by the LLM.
    """
    markers = ["--- END TEXT ---", "--- END TRANSCRIPT ---", "---"]
    for marker in markers:
        if marker in text:
            text = text.split(marker)[0]
    return text.strip()

def correct_text(raw_text: str, model_name: str) -> str:
    """
    Stage A: Correction.
    Fixes obvious HTR/OCR errors without altering meaning or structure.
    """
    if not raw_text or not raw_text.strip():
        return ""

    system_prompt = (
        "You are an expert handwriting OCR correction assistant.\n"
        "Your task is to correct spelling, punctuation, spacing, and character recognition errors "
        "in raw handwritten OCR transcripts.\n"
        "Rules:\n"
        "1. Fix obvious spelling and character mistakes.\n"
        "2. Do NOT invent new facts or details.\n"
        "3. Do NOT rewrite the author's meaning or sentence structure.\n"
        "4. Output ONLY the corrected transcript text without any introductory remarks, headers, or delimiters."
    )

    prompt = (
        f"Correct the following raw handwritten OCR transcript:\n\n"
        f"--- RAW TRANSCRIPT ---\n"
        f"{raw_text}\n"
        f"--- END TRANSCRIPT ---\n\n"
        f"Corrected text:"
    )

    res = query_ollama(prompt, model_name, system_prompt=system_prompt)
    return clean_output_markers(res)

def understand_text(corrected_text: str, model_name: str) -> str:
    """
    Stage B: Understanding.
    Produces a clean final representation preserving original meaning.
    """
    if not corrected_text or not corrected_text.strip():
        return ""

    system_prompt = (
        "You are a text understanding and formatting assistant.\n"
        "Format the input text into a clear, clean final representation.\n"
        "Rules:\n"
        "1. Preserve the exact original meaning.\n"
        "2. Do NOT hallucinate missing content or add extra information.\n"
        "3. Output ONLY the final processed text without preamble, headers, or delimiters."
    )

    prompt = (
        f"Clean and finalize the following corrected transcript:\n\n"
        f"--- CORRECTED TEXT ---\n"
        f"{corrected_text}\n"
        f"--- END TEXT ---\n\n"
        f"Final representation:"
    )

    res = query_ollama(prompt, model_name, system_prompt=system_prompt)
    return clean_output_markers(res)

def process_text_pipeline(raw_text: str, model_name: str = None, debug: bool = False) -> tuple[str, str]:
    """
    Executes Stage A (Correction) and Stage B (Understanding).
    Uses single-pass combined inference for speed, with sequential fallback and ultimate raw text fallback.
    Returns (corrected_text, final_text).
    """
    if not raw_text or not raw_text.strip():
        return "", ""

    try:
        model = get_available_model(model_name)
        if debug:
            print(f"[DEBUG] Ollama Model: {model}")

        system_prompt = (
            "You are an expert handwriting OCR correction and understanding assistant.\n"
            "Rules:\n"
            "1. Fix obvious spelling and character recognition errors without inventing details.\n"
            "2. Produce a clean final text preserving original sentence meaning.\n"
            "3. Output format MUST strictly be:\n"
            "CORRECTED:\n"
            "<corrected text>\n"
            "FINAL:\n"
            "<final text>"
        )

        prompt = f"Process this raw OCR transcript:\n\n{raw_text}\n"

        try:
            res = query_ollama(prompt, model, system_prompt=system_prompt)
            res = clean_output_markers(res)

            if "CORRECTED:" in res and "FINAL:" in res:
                parts = res.split("FINAL:")
                corrected_part = parts[0].replace("CORRECTED:", "").strip()
                final_part = parts[1].strip()
                return corrected_part, final_part
            elif "FINAL:" in res:
                final_part = res.split("FINAL:")[1].strip()
                return res.replace("FINAL:", "").strip(), final_part
            elif res.strip():
                return res.strip(), res.strip()
        except Exception as e:
            if debug:
                print(f"[DEBUG] Single-pass LLM notice ({e}), trying two-pass processing...")

        try:
            corrected = correct_text(raw_text, model_name=model)
            final = understand_text(corrected, model_name=model)
            if corrected or final:
                return corrected or raw_text, final or raw_text
        except Exception as e:
            print(f"[LLM Warning] Ollama processing notice: {e}")

    except Exception as e:
        print(f"[LLM Warning] Ollama model initialization notice: {e}")

    return raw_text, raw_text
